version: '3.7'

services:
  currency-exchange:
    image: tanayak/mmv2-currency-exchange:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8083:8083"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka

  currency-conversion:
    image: tanayak/mmv2-currency-conversion:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8084:8084"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka

  api-gateway:
    image: tanayak/mmv2-ms-api-gateway:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8765:8765"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka

  naming-server:
    image: tanayak/mmv2-ms-naming-server:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - currency-network

networks:
  currency-network: